#!/bin/sh
#
# Start linux launcher...
#

case "$1" in
  start)
		printf "Starting launcher: "
		export LC_ALL='zh_CN.utf8'
		export QT_QPA_PLATFORM=wayland
		export WESTON_DRM_MIRROR=1
		export WESTON_DRM_KEEP_RATIO=1
		export PIXMAN_USE_RGA=1
		export GST_VIDEO_CONVERT_USE_RGA=1
		export GST_V4L2_PREFERRED_FOURCC=YU12
		export QT_GSTREAMER_WINDOW_VIDEOSINK=waylandsink
		export QT_WAYLAND_CLIENT_BUFFER_INTEGRATION=wayland
		export QT_QUICK_BACKEND=software
		mkdir -p /tmp/.xdg &&  chmod 0700 /tmp/.xdg
		export XDG_RUNTIME_DIR=/tmp/.xdg
		weston --tty=2 -B=drm-backend.so --idle-time=0 --use-pixman&
		sleep 1
		/usr/bin/QLauncher &
	;;
  stop)
		killall QLauncher
		killall weston
		printf "stop finished"
        ;;
  restart|reload)
                $0 stop
                $0 start
	;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
