#!/bin/sh

case "$1" in
	start)
		sleep 5 && echo ondemand > /sys/bus/cpu/devices/cpu0/cpufreq/scaling_governor && echo "set governor ondemand ok" &
		;;
	stop)
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
exit 0
