#!/bin/sh


# Start all init scripts in /etc/preinit.d
# executing them in numerical order.
#
for i in /etc/preinit.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
    esac
done

