#!/bin/sh
#
# Start bootanimation
#

start() {
	printf "Starting bootanimation: "
	start-stop-daemon -b -S -q -m -p /var/run/modeset.pid --exec /usr/bin/modeset 
	echo "OK"
}

stop() {
	printf "Stopping bootanimation: "
	start-stop-daemon -K -q -p /var/run/modeset.pid
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
