CALLFUNIPC_SITE = $(TOPDIR)/../external/CallFunIpc
CALLFUNIPC_SITE_METHOD = local

CALLFUNIPC_INSTALL_STAGING = YES

CALLFUNIPC_DEPENDENCIES = libgdbus

ifeq ($(BR2_PACKAGE_CALLFUNIPC_DEMO),y)
CALLFUNIPC_CONF_OPTS += -DDEMO=ON
endif

ifeq ($(BR2_PACKAGE_RK_OEM), y)
CALLFUNIPC_INSTALL_TARGET_OPTS = DESTDIR=$(BR2_PACKAGE_RK_OEM_INSTALL_TARGET_DIR) install/fast
CALLFUNIPC_DEPENDENCIES += rk_oem
endif

$(eval $(cmake-package))
