#!/bin/sh

connman_dir=/userdata/connman

case "$1" in
	start)
		[ ! -d "$connman_dir" ] && mkdir -p "$connman_dir"
		[ ! -L "/var/lib/connman" ] && ln -sf /userdata/connman /var/lib/connman
		;;
	stop)
		printf "$0 stop finished\n"
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
exit 0
