LIBGDBUS_SITE = $(TOPDIR)/../app/libgdbus
LIBGDBUS_SITE_METHOD = local

LIBGDBUS_INSTALL_STAGING = YES

LIBGDBUS_DEPENDENCIES = libglib2 dbus

ifeq ($(BR2_PACKAGE_RK_OEM), y)
LIBGDBUS_INSTALL_TARGET_OPTS = DESTDIR=$(BR2_PACKAGE_RK_OEM_INSTALL_TARGET_DIR) install/fast
LIBGDBUS_DEPENDENCIES += rk_oem
endif

$(eval $(cmake-package))
