#!/bin/sh
#
# Start init
#

start() {
	printf "Starting init...\n "
        echo performance > /sys/bus/cpu/devices/cpu0/cpufreq/scaling_governor
	echo "set performance OK"
}

stop() {
	printf "Stopping init...\n"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
