#!/bin/sh
#
# Start linux launcher...
#

case "$1" in
  start)
		printf "Starting launcher: "
		export LC_ALL='en_US.utf8'

		export WESTON_DRM_MIRROR=0
		export WESTON_DRM_PREFER_EXTERNAL=1

		#for QLauncher wayland
		mkdir -p /tmp/.xdg &&  chmod 0700 /tmp/.xdg
		export XDG_RUNTIME_DIR=/tmp/.xdg
		weston --tty=2 --idle-time=0&
		/usr/local/share/scripts/bc.sh
		retroarch -c /sdcard/settings/retroarch/retroarch.cfg &
	;;
  stop)
		killall weston
		printf "stop finished"
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
