################################################################################
#
# EmulationStation FCAMOD 
#
################################################################################

EMULATIONSTATION_FCAMOD_VERSION = 37744aef1f06b08c6cd2805584ec5d3283d2887c 
EMULATIONSTATION_FCAMOD_SITE = https://github.com/christianhaitian/EmulationStation-fcamod.git
EMULATIONSTATION_FCAMOD_SITE_METHOD = git
EMULATIONSTATION_FCAMOD_GIT_SUBMODULES = YES
EMULATIONSTATION_FCAMOD_LICENSE = MIT
EMULATIONSTATION_FCAMOD_DEPENDENCIES = sdl2 sdl2_mixer libfreeimage freetype alsa-lib pulseaudio \
	libcurl openssl libzip ffmpeg 

#ifeq ($(BR2_PACKAGE_HAS_LIBGL),y)
#EMULATIONSTATION_FCAMOD_DEPENDENCIES += libgl
#endif

#ifeq ($(BR2_PACKAGE_HAS_LIBGLES),y)
EMULATIONSTATION_FCAMOD_DEPENDENCIES += libgles
EMULATIONSTATION_FCAMOD_CONF_OPTS += -DGLES=ON
#endif

define EMULATIONSTATION_FCAMOD_RPI_FIXUP
	$(SED) 's|/opt/vc/include|$(STAGING_DIR)/usr/include|g' $(@D)/CMakeLists.txt
	$(SED) 's|/opt/vc/lib|$(STAGING_DIR)/usr/lib|g' $(@D)/CMakeLists.txt
	$(SED) 's|/usr/lib|$(STAGING_DIR)/usr/lib|g' $(@D)/CMakeLists.txt
endef

EMULATIONSTATION_FCAMOD_PRE_CONFIGURE_HOOKS += EMULATIONSTATION_FCAMOD_RPI_FIXUP

ifeq ($(BR2_ENABLE_DEBUG),y)
EMULATIONSTATION_FCAMOD_CONF_OPTS += -DCMAKE_BUILD_TYPE=Debug
endif

EMULATIONSTATION_FCAMOD_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
EMULATIONSTATION_FCAMOD_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
EMULATIONSTATION_FCAMOD_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
EMULATIONSTATION_FCAMOD_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
EMULATIONSTATION_FCAMOD_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
EMULATIONSTATION_FCAMOD_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
EMULATIONSTATION_FCAMOD_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
EMULATIONSTATION_FCAMOD_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
EMULATIONSTATION_FCAMOD_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_EXE)"
EMULATIONSTATION_FCAMOD_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_EXE)"
EMULATIONSTATION_FCAMOD_CONF_OPTS += -DCMAKE_LINKER_EXE_FLAGS="$(COMPILER_COMMONS_LDFLAGS_EXE)"
EMULATIONSTATION_FCAMOD_CONF_OPTS += -DOPTION_RECALBOX_PRODUCTION_BUILD=true

$(eval $(cmake-package))
