RKFFPLAY_SITE = $(TOPDIR)/../app/rkffplay
RKFFPLAY_SITE_METHOD = local
RKFFPLAY_INSTALL_STAGING = YES
RKFFPLAY_DEPENDENCIES = sdl2 ffmpeg host-pkgconf libion rkfb linux-rga mpp alsa-lib

RKFFPLAY_CONF_OPTS += -DCONFIG_ROCKCHIP_PLATEFORM=rv1108

RKFFPLAY_CONF_OPTS += "-DCMAKE_INSTALL_STAGING=$(STAGING_DIR)" \
	"-DFFMPEG_BUILDDIR=$(FFMPEG_BUILDDIR)"

$(eval $(cmake-package))
