DEVICE_MANAGER_SITE = $(TOPDIR)/../app/device_manager
DEVICE_MANAGER_SITE_METHOD = local
DEVICE_MANAGER_INSTALL_STAGING = YES

# add dependencies
DEVICE_MANAGER_DEPENDENCIES = hal adk messenger

ifeq ($(BR2_PACKAGE_DEVICE_MANAGER_IPC_NANOMSG),y)
    DEVICE_MANAGER_DEPENDENCIES += adk messenger
    DEVICE_MANAGER_CONF_OPTS += -DENABLE_IPC_NANOMSG=1
endif

ifeq ($(BR2_PACKAGE_DEVICE_MANAGER_STORAGE_DEVICE),y)
    DEVICE_MANAGER_CONF_OPTS += -DENABLE_STORAGE_DEVICE=1
endif

ifeq ($(BR2_PACKAGE_DEVICE_MANAGER_WLAN_DEVICE),y)
    DEVICE_MANAGER_CONF_OPTS += -DENABLE_WLAN_DEVICE=1
endif

$(eval $(cmake-package))
