ADK_SITE = $(TOPDIR)/../framework/adk
ADK_SITE_METHOD = local
ADK_INSTALL_STAGING = YES

# add dependencies
ADK_DEPENDENCIES = libion

ifeq ($(BR2_PACKAGE_ADK_MEDIA_WAV_PLAYBACK),y)
    ADK_DEPENDENCIES += alsa-lib
    ADK_CONF_OPTS += -DENABLE_WAV_PLAYBACK=1
endif

ifeq ($(BR2_PACKAGE_ADK_RKMEDIA),y)
	ADK_DEPENDENCIES += rkmedia
	ADK_CONF_OPTS += -DENABLE_ADK_RKMEDIA=1

ifeq ($(BR2_PACKAGE_ADK_RKMEDIA_OGG_PLAYBACK),y)
    ADK_DEPENDENCIES += alsa-lib
    ADK_CONF_OPTS += -DENABLE_OGG_PLAYBACK=1
endif

ifeq ($(BR2_PACKAGE_ADK_RKMEDIA_H264_ENCODE),y)
	ADK_DEPENDENCIES += mpp
	ADK_CONF_OPTS += -DENABLE_H264_ENCODE=1
endif

ifeq ($(BR2_PACKAGE_ADK_RKMEDIA_MP4_MUXER),y)
    ADK_DEPENDENCIES += ffmpeg
    ADK_CONF_OPTS += -DENABLE_MP4_MUXER=1
endif

ifeq ($(BR2_PACKAGE_ADK_RKMEDIA_RTSP_STREAM),y)
    ADK_DEPENDENCIES += live555
    ADK_CONF_OPTS += -DENABLE_RTSP_STREAM=1
endif
endif

$(eval $(cmake-package))
